### ISSUE TITLE
dependency install broken

### ISSUE THREAD

**Issue by voegtlel** [JonasT/drudder#4]
When starting for the first time, the user is offered an automatic installation of dependencies:
drudder: warning: missing components detected: PyYAML, docker-machine.

After confirming, the installer gets stuck in an infinite loop in

```
Traceback (most recent call last):
  File "/usr/bin/drudder", line 1492, in <module>
    Installer.check_and_install_missing()
  File "/usr/bin/drudder", line 764, in check_and_install_missing
    Installer.install_yaml()
  File "/usr/bin/drudder", line 846, in install_yaml
    yaml_source_link = extract_source_link()
```

Comment: Maybe crawling can be better done by regex?

**Comment by JonasT** [comment]
Thanks for the report! It should work again with the latest master.
